version: "2.0"

services:
  web:
    image: ahmadhassan83/suka-forever:1672147828
    env:
      - 'url=https://sukaverse.club'    
    expose:
      - port: 9090
        as: 80
        accept:
          - "sukaverse.club"    
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 512Mi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000
deployment:
  web:
    dcloud:
      profile: web
      count: 1
