name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2    
    - name: install emulators
      run: docker run --rm --privileged tonistiigi/binfmt --install all
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - name: Build the Docker image
      run: docker buildx build . --file Dockerfile --push --platform=linux/arm,linux/arm64/v8,linux/amd64 -t ahmadhassan83/suka-forever:$(date +%s) 
